# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# -----------------    variables ------------------
# variables global que existiran dentro de todo el pipeline
variables:
  resourceGroup: 'microservices'
  containerName: 'hello-world-6'
  imageName: 'devs4j/hello-world-06'
  dnsName: 'hello-world-06-123456'
# -----------------    variables ------------------

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
